
import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'cab_go': 'CabGo Rider',
      'login': 'Log In',
      'logout': 'Log Out',
      'home': 'Home',
      'search': 'Search',
      'get_started': 'Get Started',
      'letsRide': "CabGo",
      'confirmRide': "CabGo",
      'enterPhone': "Enter Phone Number",
      'submit': "Submit",
      'cancel': "Cancel",
      'emailLogin': "Login with Email",
      'googleLogin': "Login with Google",
      'facebookLogin': "Login with Facebook",
      'appleLogin': "Login with Apple",
      'skip': "Skip",
      'searchDest': "Search Destination",
      'fairOffered': "offer a fare",
      'sendRequest': "Send Request",
      'wait': "Please wait...",
      'sent': "Request Sent",
      'requestSent': "Your ride request has been sent.",
      'driverContact': "A driver will contact you soon.",
      'setDest': "Set Destination",
      'pickL': "Pickup location",
      'whereTo': "Where to?",
    },
    'de_DE': {
      'cab_go': 'CabGo Fahrer/Fahrerin',
      'login': 'Einloggen',
      'logout': 'Ausloggen',
      'home': 'Zuhause',
      'search': 'Suche',
      'get_started': 'Loslegen',
      'letsRide': 'CabGo',
      'confirmRide': "CabGo",
      'enterPhone': "Telefonnummer eingeben",
      'submit': "einreichen",
      'cancel': "stornieren",
      'googleLogin': "Melden Sie sich mit Google an",
      'emailLogin': "Melden Sie sich mit E-Mail an",
      'facebookLogin': "Mit Facebook einloggen",
      'appleLogin': "Melden Sie sich bei Apple an",
      'skip': "überspringen",
      'searchDest': "Ziel ort",
      'fairOffered': "Biten sie ein Preis an",
      'sendRequest': "Anfrage senden",
      'wait': "Warten Sie mal...",
      'sent': "Anfrage geschickt",
      'requestSent': "Ihre Fahrtanfrage wurde gesendet.",
      'driverContact': "Ein Fahrer wird Sie bald kontaktieren.",
      'setDest': "Festgelegtes Ziel",
      'pickL': "Treffpunkt",
      'whereTo': "Wohin?",
    }
  };
}